version: '3.8'

services:
  celery_playground_celery_worker_1:
    container_name: celery_playground_celery_worker_1_dev
    build:
        context: .
        dockerfile: Dockerfile-dev
    command: poetry run celery -A celery_playground.first_steps.tasks worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=amqp://bugs:bunny@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - celery_playground_network
    healthcheck:
      test: poetry run celery inspect ping -A celery_playground.first_steps.tasks.add
      interval: 30s
      timeout: 30s
      start_period: 1m
      start_interval: 5s
      retries: 3
    depends_on:
      celery_playground_message_broker:
        condition: service_healthy
      celery_playground_results_backend:
        condition: service_healthy

  celery_playground_celery_worker_2:
    container_name: celery_playground_celery_worker_2_dev
    build:
        context: .
        dockerfile: Dockerfile-dev
    command: poetry run celery -A celery_playground.getting_started worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=amqp://bugs:bunny@rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - celery_playground_network
    healthcheck:
      test: poetry run celery inspect ping -A celery_playground.getting_started.tasks.add
      interval: 30s
      timeout: 30s
      start_period: 1m
      start_interval: 5s
      retries: 3
    depends_on:
      celery_playground_message_broker:
        condition: service_healthy
      celery_playground_results_backend:
        condition: service_healthy

  celery_playground_message_broker:
    container_name: celery_playground_message_broker_dev
    # 3.12.6 Alpine
    image: rabbitmq@sha256:02de6888429b4da4ea4b5032bce91e942a1c9e7c77191b97f60efe1efa07b12e
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=bugs
      - RABBITMQ_DEFAULT_PASS=bunny
    networks:
      - celery_playground_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      start_period: 1m
      start_interval: 5s
      retries: 3

  celery_playground_results_backend:
    container_name: celery_playground_results_backend_dev
    # 7.1.2 Alpine
    image: redis@sha256:343e6546f35877801de0b8580274a5e3a8e8464cabe545a2dd9f3c78df77542a
    hostname: redis
    networks:
      - celery_playground_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 30s
      start_period: 1m
      start_interval: 5s
      retries: 3

networks:
  celery_playground_network:
